from pathlib import Path

# Permanent production smoke generated by e3_patch.py: use Chromium touch input instead of synthetic PointerEvent.
smoke = Path('.github/production-smoke.mjs')
text = smoke.read_text()
old = '''  const forwardButton = page.getByRole("button", { name: "Move forward", exact: true });
  await forwardButton.dispatchEvent("pointerdown", { pointerId: 71, pointerType: "touch", isPrimary: true });
  await page.waitForTimeout(320);
  await forwardButton.dispatchEvent("pointerup", { pointerId: 71, pointerType: "touch", isPrimary: true });
  await page.waitForTimeout(120);'''
new = '''  const forwardButton = page.getByRole("button", { name: "Move forward", exact: true });
  await forwardButton.scrollIntoViewIfNeeded();
  const forwardBox = await forwardButton.boundingBox();
  assert(forwardBox, "mobile spatial: Move forward has no bounding box");
  const movementCdp = await context.newCDPSession(page);
  const moveX = forwardBox.x + forwardBox.width / 2;
  const moveY = forwardBox.y + forwardBox.height / 2;
  await movementCdp.send("Input.dispatchTouchEvent", { type: "touchStart", touchPoints: [{ x: moveX, y: moveY, id: 71, radiusX: 4, radiusY: 4, force: 1 }] });
  await page.waitForTimeout(320);
  await movementCdp.send("Input.dispatchTouchEvent", { type: "touchEnd", touchPoints: [] });
  await page.waitForTimeout(120);'''
if old not in text:
    raise SystemExit('production smoke mobile pointer snippet not found')
smoke.write_text(text.replace(old, new, 1))

# Temporary detailed validator uses the same real touch path.
validator = Path('scripts/e3_validate_v2.mjs')
text = validator.read_text()
old = '''    const forward = page.getByRole("button", { name: "Move forward", exact: true });
    await forward.dispatchEvent("pointerdown", { pointerId: 91, pointerType: "touch", isPrimary: true });
    await page.waitForTimeout(650);
    await forward.dispatchEvent("pointerup", { pointerId: 91, pointerType: "touch", isPrimary: true });
    await page.waitForTimeout(120);'''
new = '''    const forward = page.getByRole("button", { name: "Move forward", exact: true });
    await forward.scrollIntoViewIfNeeded();
    const forwardBox = await forward.boundingBox();
    assert(forwardBox, "mobile Move forward has no bounding box");
    const cdp = await context.newCDPSession(page);
    const moveX = forwardBox.x + forwardBox.width / 2;
    const moveY = forwardBox.y + forwardBox.height / 2;
    await cdp.send("Input.dispatchTouchEvent", { type: "touchStart", touchPoints: [{ x: moveX, y: moveY, id: 91, radiusX: 4, radiusY: 4, force: 1 }] });
    await page.waitForTimeout(650);
    await cdp.send("Input.dispatchTouchEvent", { type: "touchEnd", touchPoints: [] });
    await page.waitForTimeout(120);'''
if old not in text:
    raise SystemExit('detailed validator mobile pointer snippet not found')
validator.write_text(text.replace(old, new, 1))
